### PR TITLE
ENH try again without pcre pin

### PR DESCRIPTION
**Pull request by beckermr**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by beckermr** [comment]
@conda-forge-admin rerender

**Comment by beckermr** [comment]
@conda-forge/libgsf this is ready for review! 

It passes make check and the command line smoke tests so I think it is safe to merge. 

This will help unblock the glib migration I think.

**Comment by sebastian-luna-valero** [comment]
Thanks @beckermr 

`pcre` was pinned in the past to make `libgsf` work. Since `pcre` has been updated, it looks like it works with the latest version without pinning.

I was wondering whether we need to add the following to this recipe:
```
  run:
    - {{ pin_compatible('pcre') }}
```

What do you think?

Many thanks,
Sebastian

**Comment by beckermr** [comment]
`pcre` has a run export in conda build which adds the correct runtime constraint already. See here: https://github.com/conda-forge/pcre-feedstock/blob/master/recipe/meta.yaml#L18

Thus we do not need to add anything in this recipe.

**Comment by sebastian-luna-valero** [comment]
I see, thanks!

Would you like to be a package maintainer for `libgsf`?

**Comment by beckermr** [comment]
No thank you! I am a member of core and am trying to unblock a migration. :)

**Comment by sebastian-luna-valero** [comment]
Alright, thanks!

**Comment by beckermr** [comment]
Thank you for being a great maintainer! :)

**Pull request merged**
